### ISSUE TITLE
Suggestion: Show block folding, and/or tabs/spaces

### ISSUE THREAD

**Issue by neeklamy** [jasonswett/angular-for-rails-developers-issues#3]
It would be a _lot_ easier to follow the longer code blocks if block folding were illustrated somehow.

I had a slight issue with the reference code for `spec/controllers/book_controller_spec.rb`, with it spanning three pages, and with the multiple edits required, I deleted an `end` and took some time to find where it was missing.

Line numbers would be nice too, something like this:

![code-folding](https://cloud.githubusercontent.com/assets/155358/18218079/5236701e-7158-11e6-872a-e0d9f61e620a.png)

If not block folding, how about showing tabs or spaces:

![show-invisbles](https://cloud.githubusercontent.com/assets/155358/18218274/7b96d92a-7159-11e6-88c6-fad3057ea4c6.png)

**Comment by jasonswett** [comment]
Also a good idea. In future versions I should probably include the Git repo of not just the code that comes with the book but the markdown for the book as well. I'm still trying to figure out a good format.
