### ISSUE TITLE
Pushed to Heroku, but app isn’t up to date

### ISSUE THREAD

**Issue by neeklamy** [jasonswett/angular-for-rails-developers-issues#8]
I’ve finished the book, committed the change locally and ran `git remote show heroku`, but the Heroku application isn’t up to date. Any ideas why?

I’ve tried rebooting the app (through the Heroku web dashboard, _Overview → More → Restart all dynos_) and `heroku ps:restart`.

The Heroku repository reports it’s up to date:

```
# git remote show heroku
* remote heroku
  Fetch URL: https://git.heroku.com/secure-depths-61266.git
  Push  URL: https://git.heroku.com/secure-depths-61266.git
  HEAD branch: master
  Remote branch:
    master tracked
  Local ref configured for 'git push':
    master pushes to master (up to date)
```

And:

```
# git ls-remote heroku
11ac8180b8748fbd4f50e955c791f209eaa74400    HEAD
11ac8180b8748fbd4f50e955c791f209eaa74400    refs/heads/master
```

And the Heroku app: https://secure-depths-61266.herokuapp.com

And I check back a few hours later and it’s up-to-date with my local git repository. Any idea why there would be a lag between push and updating? Is there some kind of caching going on? (I really should have tried in a different browser, this was all observed using Google Chrome.)

**Comment by jasonswett** [comment]
That's really weird. I've never had that happen in years of using Heroku. I have no idea why that happened, sorry.

Closing since I think this is probably not a book-related issue.
